version: '2.1'
networks: {}
volumes:
  etc: {}
  media: {}
  run: {}
services:
  motioneye-netpi:
    build: ./
    tty: true
    restart: unless-stopped
# network mode host so we can be discoverable with Avahi
    network_mode: host
    volumes:
      - 'etc:/etc/motioneye'
      - 'media:/var/lib/motioneye'
      - 'run:/var/run/motion'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.resin-api: '1'
      io.balena.features.balena-socket: '1'